### ISSUE TITLE
How to change the line color when drawing the polygon?

### ISSUE THREAD

**Issue by calvinxiu** [Wildhoney/Leaflet.FreeDraw#45]
Hi all, the css in example had demo how to change the color after create the polygon, but how can i change the color when i drawing the polygon? current color is purple, i want to change it to blue.

BTW. Freedraw is the best draw plugin :)

**Comment by Wildhoney** [comment]
Thanks, Calvin! :beers:

It should be as easy as adding a little bit of CSS:

```css
path {
    stroke: blue;
}
```

Although [I've just added a class name](https://github.com/Wildhoney/Leaflet.FreeDraw/commit/13b782346adb4118aaaeb67f228a62aa97307aaf) to that line to distinguish it from any other potential `path` nodes, so now you can use the above CSS with `drawing-line`:

```css
path.drawing-line {
    stroke: blue;
}
```

Hope this helps! :+1:
