### ISSUE TITLE
Polygon style lost on edit

### ISSUE THREAD

**Issue by hrishiballal** [Wildhoney/Leaflet.FreeDraw#64]
I am having a peculiar issue while polygon editing. When I have a polygon and editing is enabled the handles appear as normal below: 
![before](https://cloud.githubusercontent.com/assets/1588744/11037358/453b001c-86f5-11e5-8d93-aeb2e8cfd03a.png)

However after editing the color of the polygon is lost, instead of the default blue, it should be pink as before editing. Can someone please help as to how this can be fixed / why this is happending? I tried to debug it but could not figure out what is going on in the _recreateEdges method. 
![after](https://cloud.githubusercontent.com/assets/1588744/11037419/8b4876b6-86f5-11e5-9cc5-c19f0b0dc523.png)

**Comment by Wildhoney** [comment]
How are you applying the styling?

You can [see in the example](http://freedraw.herokuapp.com/css/Map.css) how to do it:

```css
section.map g path {
    transition: all 0.25s;
    stroke-width: 4px;
    stroke-opacity: 1;
    stroke: #D7217E;
    position: absolute;
    z-index: 1001;
    fill: #D7217E;
    fill-opacity: .75;
    -webkit-filter: none;
}
```
